apiVersion: v1
kind: ServiceAccount
metadata:
  name: the-gram
  namespace: the-gram
---
apiVersion: v1
kind: Service
metadata:
  name: the-gram-profile-service
  namespace: the-gram
spec:
  type: NodePort
  selector:
    app: the-gram-profile
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-gram-profile
  namespace: the-gram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-gram-profile
  template:
    metadata:
      labels:
        app: the-gram-profile
    spec:
      containers:
        - name: the-gram-profile
          image: gcr.io/s62-1-278920/the-gram-profile:5fe5396
          ports:
            - containerPort: 80
              name: http
        - name: default-http-backend
          # Any image is permissible as long as:
          # 1. It serves a 404 page at /
          # 2. It serves 200 on a /healthz endpoint
          image: k8s.gcr.io/ingress-gce-404-server-with-metrics-amd64:v1.6.0
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
      serviceAccountName: the-gram
