version: 2.1
orbs:
  win: circleci/windows@1.0.0
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.0.2
jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:3.1
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: TheGramProfile
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: TheGramProfile
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
        image: the-gram-profile
        tag: "v2.4" #Change version number e.g to 'v3' when updating application
      - gcr/push-image:
        image: the-gram-profile
        tag: "v2.4" #Change version number e.g to 'v3' when updating application

  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/init
      # Update a deployment Docker image.
      - gcp-gke/rollout-image:
        deployment: the-gram-profile
        container: the-gram-profile
        image: gcr.io/$GCP_PROJECT_ID/the-gram-profile:v2.4 # change version when updating
workflows:
  build_update_deploy:
    jobs:
      - build
      - Build-Push-Image-Docker:
        requires:
          - build
      - deploy:
        requires:
          - Build-Push-Image-Docker
  # dockerize:
  #   machine: true
  #   steps:
  #     - checkout
  #     # start proprietary DB using private Docker image
  #     # with credentials stored in the UI
  #     - name: Sign in to docker
  #       run: |
  #         echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
  #     # build the application image
  #     - name: Build image
  #       run: docker build -t tommygoossens/the-gram-profile:$CIRCLE_BRANCH .
  #     # deploy the image
  #     - name: Publish docker image to registry
  #       run: docker push tommygoossens/the-gram-profile:$CIRCLE_BRANCH
