version: 2.1
orbs:
  windows: circleci/windows@2.2.0
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.0.2
jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: TheGramProfile
      - run:
          name: Build
          command: dotnet build -c Development
          working_directory: TheGramProfile
  BuildPushImageDocker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: the-gram-profile
          tag: "v2.4" #Change version number e.g to 'v3' when updating application
      - gcr/push-image:
          image: the-gram-profile
          tag: "v2.4" #Change version number e.g to 'v3' when updating application

  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/init
      # Update a deployment Docker image.
      - gcp-gke/rollout-image:
          cluster: the-gram-k8s
          deployment: the-gram-profile
          container: the-gram-profile
          image: gcr.io/$GCP_PROJECT_ID/the-gram-profile:v2.4 # change version when updating
workflows:
  build_update_deploy:
    jobs:
      - build
      - BuildPushImageDocker:
          requires:
            - build
      - deploy:
          requires:
            - BuildPushImageDocker
