version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          echo "$DockerPassword" | docker login --username $DockerUsername --password-stdin

      # build the application image
      - run: docker build -t tommygoossens/the-gram-profile:latest:$CIRCLE_BRANCH .

      # deploy the image
      - run: docker push tommygoossens/the-gram-profile:latest:$CIRCLE_BRANCH
